from __future__ import annotations

from app.models import (
    AppState,
    DocumentTemplate,
    FoundingCheck,
    FounderCase,
    KnowledgeItem,
)


DISCLAIMER = "FoundAItion gibt eine strukturierende Orientierung und ersetzt keine Rechtsberatung."


def build_demo_state() -> AppState:
    founder_case = FounderCase(
        userName="Anna",
        companyName="Demo Kulturverein i.G.",
        foundersCount=7,
        wantsLimitedLiability=False,
        hasWebsite=False,
        processesPersonalData=True,
        usesAiTools=False,
        selectedLegalForm=None,
    )

    checks = [
        FoundingCheck(
            id="association_purpose",
            category="Vorbereitung & Konzept",
            title="Vereinszweck definieren",
            description="Der e.V.-Zweck muss ideell und nicht auf einen wirtschaftlichen Geschäftsbetrieb ausgerichtet sein.",
            status="required",
            required_document_types=["Vereinszweckbeschreibung"],
            matched_document_ids=[],
            explanation="Formuliere den Vereinszweck so konkret, dass er für Satzung, Registergericht und spätere Tätigkeiten nachvollziehbar bleibt.",
        ),
        FoundingCheck(
            id="founding_members",
            category="Vorbereitung & Konzept",
            title="Mindestens sieben Gründungsmitglieder sichern",
            description="Für die Eintragung zum e.V. sollen mindestens sieben Mitglieder an der Gründung beteiligt sein.",
            status="required",
            required_document_types=["Gründungsmitgliederliste"],
            matched_document_ids=[],
            explanation="Halte die sieben Gründungsmitglieder frühzeitig strukturiert fest, damit Satzung und Gründungsversammlung sauber vorbereitet werden können.",
        ),
        FoundingCheck(
            id="association_name",
            category="Vorbereitung & Konzept",
            title="Vereinsnamen prüfen und festlegen",
            description="Der Vereinsname muss unterscheidbar sein und in der Satzung geführt werden.",
            status="missing",
            required_document_types=["Namensprüfung"],
            matched_document_ids=[],
            explanation="Eine dokumentierte Namensprüfung reduziert das Risiko einer Zurückweisung durch das Registergericht.",
        ),
        FoundingCheck(
            id="association_seat",
            category="Vorbereitung & Konzept",
            title="Vereinssitz bestimmen",
            description="Der Sitz des Vereins bestimmt unter anderem das zuständige Registergericht.",
            status="missing",
            required_document_types=["Vereinssitz-Nachweis"],
            matched_document_ids=[],
            explanation="Lege den Sitz früh fest, damit Satzung und Registeranmeldung konsistent bleiben.",
        ),
        FoundingCheck(
            id="nonprofit_strategy",
            category="Satzung",
            title="Gemeinnützigkeit entscheiden",
            description="Prüfe, ob der Verein die Anforderungen an eine spätere Gemeinnützigkeit erfüllen soll.",
            status="check",
            required_document_types=["Gemeinnützigkeitskonzept"],
            matched_document_ids=[],
            explanation="Die Entscheidung wirkt sich direkt auf Satzung, Vermögensbindung und spätere Finanzamtskommunikation aus.",
        ),
        FoundingCheck(
            id="legal_form_path",
            category="Vorbereitung & Konzept",
            title="POC-Pfad für den e.V. aktivieren",
            description="Dokumentiert, dass der Pilot aktuell auf den eingetragenen Verein ausgerichtet ist.",
            status="check",
            required_document_types=[],
            matched_document_ids=[],
            explanation="Wird gesetzt, sobald der e.V.-Pilotpfad in FoundAItion aktiviert wird.",
        ),
        FoundingCheck(
            id="nonprofit_clauses",
            category="Gemeinnützigkeit",
            title="Gemeinnützigkeitsklauseln sauber einbauen",
            description="Bei geplanter Gemeinnützigkeit müssen Selbstlosigkeit, Ausschließlichkeit, Unmittelbarkeit und Vermögensbindung sauber geregelt werden.",
            status="missing",
            required_document_types=["Vereinssatzung"],
            matched_document_ids=[],
            explanation="Die Satzung sollte sich eng an der Mustersatzung zur Abgabenordnung orientieren, um spätere Beanstandungen zu vermeiden.",
        ),
        FoundingCheck(
            id="founding_meeting",
            category="Gründungsversammlung",
            title="Gründungsversammlung vorbereiten und dokumentieren",
            description="Einladung, Tagesordnung und Beschlüsse der Gründungsversammlung müssen strukturiert dokumentiert werden.",
            status="missing",
            required_document_types=["Gründungsprotokoll"],
            matched_document_ids=[],
            explanation="Das Gründungsprotokoll ist eines der Kernstücke für Registeranmeldung und Nachvollziehbarkeit des Gründungsvorgangs.",
        ),
        FoundingCheck(
            id="board_election",
            category="Gründungsversammlung",
            title="Vorstand wählen und Wahl dokumentieren",
            description="Die Bestellung des Vorstands erfolgt über die Mitgliederversammlung und sollte separat belegbar sein.",
            status="missing",
            required_document_types=["Vorstandswahlprotokoll"],
            matched_document_ids=[],
            explanation="Eine klar protokollierte Vorstandswahl ist für Registergericht und spätere Vertretungsfragen besonders wichtig.",
        ),
        FoundingCheck(
            id="signed_statute",
            category="Gründungsversammlung",
            title="Satzung von mindestens sieben Mitgliedern unterzeichnen lassen",
            description="Die Satzung sollte von mindestens sieben Gründungsmitgliedern unterschrieben und datiert sein.",
            status="missing",
            required_document_types=["Unterzeichnete Satzung"],
            matched_document_ids=[],
            explanation="Ohne unterzeichnete Satzung fehlt ein zentrales Registerdokument für die Eintragung.",
        ),
        FoundingCheck(
            id="registry_application",
            category="Notartermin",
            title="Anmeldung zum Vereinsregister vorbereiten",
            description="Der Vorstand meldet den Verein beim zuständigen Amtsgericht an und reicht die erforderlichen Unterlagen ein.",
            status="missing",
            required_document_types=["Vereinsregister-Anmeldung"],
            matched_document_ids=[],
            explanation="Bereite die Registeranmeldung mit Satzung, Protokollen und Vorstandsunterlagen vollständig vor.",
        ),
        FoundingCheck(
            id="notarization",
            category="Notartermin",
            title="Notarielle Beglaubigung der Anmeldung einholen",
            description="Die Unterschriften des Vorstands unter der Registeranmeldung müssen notariell beglaubigt werden.",
            status="missing",
            required_document_types=["Notarielle Beglaubigung"],
            matched_document_ids=[],
            explanation="Die notarielle Beglaubigung ist ein häufiger Stolperstein, weil sie Kosten verursacht und oft zu spät eingeplant wird.",
        ),
        FoundingCheck(
            id="tax_eligibility_request",
            category="Gemeinnützigkeit",
            title="Feststellung der Satzungsmäßigkeit beantragen",
            description="Bei geplanter Gemeinnützigkeit sollte früh der Antrag auf Feststellung der Satzungsmäßigkeit gestellt werden.",
            status="check",
            required_document_types=["Antrag Satzungsmäßigkeit"],
            matched_document_ids=[],
            explanation="So kann der Verein frühzeitig mit dem Finanzamt abstimmen, ob die Satzung die steuerlichen Anforderungen erfüllt.",
        ),
        FoundingCheck(
            id="bookkeeping_setup",
            category="Gemeinnützigkeit",
            title="Buchhaltung und Aufzeichnungen aufsetzen",
            description="Einnahmen, Ausgaben und die tatsächliche Geschäftsführung sollten von Beginn an ordnungsgemäß dokumentiert werden.",
            status="check",
            required_document_types=["Buchhaltungs-Setup"],
            matched_document_ids=[],
            explanation="Gerade für gemeinnützige Vereine ist die laufende Nachweisführung gegenüber dem Finanzamt zentral.",
        ),
        FoundingCheck(
            id="bank_account",
            category="Gemeinnützigkeit",
            title="Vereinskonto eröffnen",
            description="Nach Registereintragung sollte ein Vereinskonto für den operativen Zahlungsverkehr eingerichtet werden.",
            status="check",
            required_document_types=["Vereinskonto-Nachweis"],
            matched_document_ids=[],
            explanation="Ein dokumentiertes Vereinskonto erleichtert spätere Buchhaltung und saubere Mittelverwendung.",
        ),
        FoundingCheck(
            id="annual_meeting",
            category="Laufende Pflichten",
            title="Jährliche Mitgliederversammlung einplanen",
            description="Nach der Gründung müssen die satzungsmäßigen Versammlungen und Beschlüsse fortlaufend organisiert werden.",
            status="check",
            required_document_types=[],
            matched_document_ids=[],
            explanation="Plane turnusmäßige Mitgliederversammlungen früh mit ein, damit Wahl- und Berichtspflichten sauber laufen.",
        ),
        FoundingCheck(
            id="board_change_process",
            category="Laufende Pflichten",
            title="Vorstandsänderungen rechtzeitig ans Register melden",
            description="Jede Änderung des Vorstands sollte später zeitnah zum Vereinsregister gemeldet werden.",
            status="check",
            required_document_types=[],
            matched_document_ids=[],
            explanation="Verspätete Registermeldungen führen in der Praxis schnell zu Problemen bei Vertretung und Kontoangelegenheiten.",
        ),
        FoundingCheck(
            id="statute_change_process",
            category="Laufende Pflichten",
            title="Satzungsänderungen als registerpflichtigen Prozess vormerken",
            description="Satzungsänderungen werden erst mit Eintragung im Vereinsregister wirksam.",
            status="check",
            required_document_types=[],
            matched_document_ids=[],
            explanation="Dokumentiere den Prozess für spätere Satzungsänderungen direkt mit, damit Folgeänderungen nicht informell hängen bleiben.",
        ),
        FoundingCheck(
            id="member_threshold",
            category="Laufende Pflichten",
            title="Mindestmitgliederzahl dauerhaft im Blick behalten",
            description="Nach der Eintragung darf die Mitgliederzahl nicht dauerhaft unter drei sinken.",
            status="check",
            required_document_types=[],
            matched_document_ids=[],
            explanation="Die Eintragung verlangt sieben Gründungsmitglieder, der spätere Bestand von mindestens drei Mitgliedern bleibt jedoch kritisch.",
        ),
        FoundingCheck(
            id="liability_risks",
            category="Laufende Pflichten",
            title="Haftungs- und Insolvenzrisiken transparent halten",
            description="Vorstand und ehrenamtlich tätige Mitglieder sollten Haftungsgrenzen, Freistellung und Insolvenzantragspflichten kennen.",
            status="check",
            required_document_types=[],
            matched_document_ids=[],
            explanation="Gerade die Insolvenzantragspflicht und der praktische Versicherungsschutz sollten nicht erst nach einem Vorfall betrachtet werden.",
        ),
    ]

    document_templates = [
        DocumentTemplate(
            id="template-purpose",
            title="Vereinszweckbeschreibung",
            category="Vorbereitung & Konzept",
            description="Beschreibt den ideellen Vereinszweck und grenzt ihn von wirtschaftlichen Tätigkeiten ab.",
            document_type="Vereinszweckbeschreibung",
            template_type="worksheet",
        ),
        DocumentTemplate(
            id="template-members",
            title="Gründungsmitgliederliste",
            category="Vorbereitung & Konzept",
            description="Hält die mindestens sieben Gründungsmitglieder strukturiert fest.",
            document_type="Gründungsmitgliederliste",
            template_type="checklist",
        ),
        DocumentTemplate(
            id="template-name-check",
            title="Namensprüfung",
            category="Vorbereitung & Konzept",
            description="Dokumentiert die Prüfung, ob der Vereinsname im Registerumfeld unterscheidbar ist.",
            document_type="Namensprüfung",
            template_type="checklist",
        ),
        DocumentTemplate(
            id="template-seat",
            title="Vereinssitz-Nachweis",
            category="Vorbereitung & Konzept",
            description="Beschreibt den geplanten Sitz und die zuständige Registergericht-Zuordnung.",
            document_type="Vereinssitz-Nachweis",
            template_type="worksheet",
        ),
        DocumentTemplate(
            id="template-nonprofit",
            title="Gemeinnützigkeitskonzept",
            category="Gemeinnützigkeit",
            description="Strukturiert, ob und wie die Gemeinnützigkeit von Anfang an verfolgt werden soll.",
            document_type="Gemeinnützigkeitskonzept",
            template_type="worksheet",
        ),
        DocumentTemplate(
            id="template-statute",
            title="Vereinssatzung",
            category="Satzung",
            description="Enthält Zweck, Name, Sitz, Eintragungswillen und die zentralen Vereinsregeln.",
            document_type="Vereinssatzung",
            template_type="portfolio",
        ),
        DocumentTemplate(
            id="template-founding-minutes",
            title="Gründungsprotokoll",
            category="Gründungsversammlung",
            description="Dokumentiert Satzungsbeschluss und Ablauf der Gründungsversammlung.",
            document_type="Gründungsprotokoll",
            template_type="protocol",
        ),
        DocumentTemplate(
            id="template-board-election",
            title="Vorstandswahlprotokoll",
            category="Gründungsversammlung",
            description="Hält Wahl, Zusammensetzung und Vertretung des Vorstands fest.",
            document_type="Vorstandswahlprotokoll",
            template_type="protocol",
        ),
        DocumentTemplate(
            id="template-signed-statute",
            title="Unterzeichnete Satzung",
            category="Gründungsversammlung",
            description="Die final von mindestens sieben Gründungsmitgliedern unterzeichnete Satzung.",
            document_type="Unterzeichnete Satzung",
            template_type="portfolio",
        ),
        DocumentTemplate(
            id="template-registry",
            title="Vereinsregister-Anmeldung",
            category="Notartermin",
            description="Bereitet die Registeranmeldung beim zuständigen Amtsgericht vor.",
            document_type="Vereinsregister-Anmeldung",
            template_type="checklist",
        ),
        DocumentTemplate(
            id="template-notary",
            title="Notarielle Beglaubigung",
            category="Notartermin",
            description="Dokumentiert die notarielle Beglaubigung der Anmeldung durch den Vorstand.",
            document_type="Notarielle Beglaubigung",
            template_type="evidence",
        ),
        DocumentTemplate(
            id="template-tax-status",
            title="Antrag Satzungsmäßigkeit",
            category="Gemeinnützigkeit",
            description="Unterlage für die Feststellung der Satzungsmäßigkeit beim Finanzamt.",
            document_type="Antrag Satzungsmäßigkeit",
            template_type="checklist",
        ),
        DocumentTemplate(
            id="template-bookkeeping",
            title="Buchhaltungs-Setup",
            category="Gemeinnützigkeit",
            description="Beschreibt Buchhaltung, Aufzeichnungen und Mittelverwendungslogik des Vereins.",
            document_type="Buchhaltungs-Setup",
            template_type="worksheet",
        ),
        DocumentTemplate(
            id="template-bank-account",
            title="Vereinskonto-Nachweis",
            category="Gemeinnützigkeit",
            description="Nachweis oder Notiz zur Eröffnung des Vereinskonto-Setups.",
            document_type="Vereinskonto-Nachweis",
            template_type="evidence",
        ),
    ]

    knowledge_base = [
        KnowledgeItem(
            term="e.V.",
            category="Rechtsform",
            explanation="Ein eingetragener Verein ist ein Verein mit ideellem Zweck, der durch die Eintragung ins Vereinsregister rechtlich selbst handeln kann.",
        ),
        KnowledgeItem(
            term="Rechtsfähigkeit",
            category="Rechtsform",
            explanation="Rechtsfähigkeit bedeutet, dass der Verein selbst Verträge schließen, Eigentum haben und vor Gericht auftreten kann.",
        ),
        KnowledgeItem(
            term="Vereinszweck",
            category="Vorbereitung & Konzept",
            explanation="Der Vereinszweck beschreibt, wofür der Verein da ist und was er inhaltlich erreichen möchte.",
        ),
        KnowledgeItem(
            term="Satzung",
            category="Satzung",
            explanation="Die Satzung ist das Grundregelwerk des Vereins und legt fest, wie der Verein funktioniert.",
        ),
        KnowledgeItem(
            term="Gründungsversammlung",
            category="Gründungsversammlung",
            explanation="Die Gründungsversammlung ist das erste offizielle Treffen, bei dem der Verein gegründet und die Satzung beschlossen wird.",
        ),
        KnowledgeItem(
            term="Gründungsprotokoll",
            category="Gründungsversammlung",
            explanation="Das Gründungsprotokoll hält schriftlich fest, was in der Gründungsversammlung beschlossen wurde.",
        ),
        KnowledgeItem(
            term="Mitgliederversammlung",
            category="Gründungsversammlung",
            explanation="Die Mitgliederversammlung ist das wichtigste Entscheidungsgremium des Vereins, in dem die Mitglieder abstimmen.",
        ),
        KnowledgeItem(
            term="Vorstand",
            category="Gründungsversammlung",
            explanation="Der Vorstand vertritt den Verein nach außen und kümmert sich um die laufende Organisation.",
        ),
        KnowledgeItem(
            term="Vorstandswahl",
            category="Gründungsversammlung",
            explanation="Bei der Vorstandswahl bestimmen die Mitglieder, wer den Verein führen und vertreten soll.",
        ),
        KnowledgeItem(
            term="Mitgliedsbeitrag",
            category="Gemeinnützigkeit",
            explanation="Der Mitgliedsbeitrag ist der regelmäßige Betrag, den Mitglieder an den Verein zahlen.",
        ),
        KnowledgeItem(
            term="Vereinsregister",
            category="Notartermin",
            explanation="Das Vereinsregister ist das offizielle Register, in dem eingetragene Vereine und wichtige Änderungen vermerkt werden.",
        ),
        KnowledgeItem(
            term="Registergericht",
            category="Notartermin",
            explanation="Das Registergericht ist das zuständige Amtsgericht, das über die Eintragung des Vereins entscheidet.",
        ),
        KnowledgeItem(
            term="Vereinssitz",
            category="Vorbereitung & Konzept",
            explanation="Der Vereinssitz ist der offizielle Ort des Vereins und bestimmt meist auch das zuständige Registergericht.",
        ),
        KnowledgeItem(
            term="Gemeinnützigkeit",
            category="Gemeinnützigkeit",
            explanation="Gemeinnützigkeit bedeutet, dass der Verein dem Gemeinwohl dient und dadurch steuerliche Vorteile bekommen kann.",
        ),
        KnowledgeItem(
            term="Vermögensbindung",
            category="Gemeinnützigkeit",
            explanation="Vermögensbindung heißt, dass das Vereinsvermögen bei Auflösung nicht privat verteilt werden darf, wenn der Verein gemeinnützig ist.",
        ),
        KnowledgeItem(
            term="Satzungsmäßigkeit",
            category="Gemeinnützigkeit",
            explanation="Satzungsmäßigkeit bedeutet, dass die Satzung die formalen Anforderungen erfüllt, etwa für eine mögliche Gemeinnützigkeit.",
        ),
        KnowledgeItem(
            term="Notarielle Beglaubigung",
            category="Notartermin",
            explanation="Die notarielle Beglaubigung bestätigt offiziell die Unterschriften unter der Registeranmeldung.",
        ),
        KnowledgeItem(
            term="Mindestmitgliederzahl",
            category="Laufende Pflichten",
            explanation="Für die Gründung eines e.V. werden in der Regel mindestens sieben Gründungsmitglieder benötigt.",
        ),
        KnowledgeItem(
            term="Haftung",
            category="Laufende Pflichten",
            explanation="Haftung beschreibt, wer für Fehler, Schulden oder Pflichtverletzungen des Vereins oder Vorstands einstehen muss.",
        ),
        KnowledgeItem(
            term="Satzungsänderung",
            category="Laufende Pflichten",
            explanation="Eine Satzungsänderung ist eine offizielle Änderung der Vereinsregeln und muss meist beschlossen und eingetragen werden.",
        ),
    ]

    return AppState(
        founder_case=founder_case,
        checks=checks,
        document_templates=document_templates,
        documents=[],
        evidence_records=[],
        knowledge_base=knowledge_base,
        disclaimer=DISCLAIMER,
    )
