from __future__ import annotations

from app.models import (
    AppState,
    DocumentTemplate,
    FoundingCheck,
    FounderCase,
    KnowledgeItem,
)


DISCLAIMER = "FoundAItion gibt eine strukturierende Orientierung und ersetzt keine Rechtsberatung."


def build_demo_state() -> AppState:
    founder_case = FounderCase(
        userName="Max",
        companyName="Demo Startup UG",
        foundersCount=2,
        wantsLimitedLiability=True,
        hasWebsite=True,
        processesPersonalData=True,
        usesAiTools=True,
        selectedLegalForm=None,
    )

    checks = [
        FoundingCheck(
            id="founder_profile",
            category="Basisdaten",
            title="Gründer:innenprofil erfassen",
            description="Erfasst zentrale Angaben zu Gründer:innen, Rollen und Kontaktinformationen.",
            status="required",
            required_document_types=["Gründer:innenprofil"],
            matched_document_ids=[],
            explanation="Lege die Grunddaten der beteiligten Gründer:innen strukturiert ab.",
        ),
        FoundingCheck(
            id="company_profile",
            category="Basisdaten",
            title="Unternehmensprofil erfassen",
            description="Strukturiert Name, Sitz, Zweck und zentrale Kontaktdaten des Unternehmens.",
            status="required",
            required_document_types=["Unternehmensprofil"],
            matched_document_ids=[],
            explanation="Ein kurzes Unternehmensprofil schafft die Basis für weitere Unterlagen.",
        ),
        FoundingCheck(
            id="business_address",
            category="Basisdaten",
            title="Geschäftsadresse angeben",
            description="Dokumentiert Sitz oder Geschäftsanschrift des Unternehmens.",
            status="missing",
            required_document_types=["Geschäftsadresse-Nachweis"],
            matched_document_ids=[],
            explanation="Ohne Adressnachweis bleibt dieser Punkt im Pilot offen.",
        ),
        FoundingCheck(
            id="articles_of_association",
            category="Gründungsdokumente",
            title="Gesellschaftsvertrag oder Musterstruktur vorbereiten",
            description="Bereitet die gesellschaftsrechtliche Grundstruktur der UG vor.",
            status="missing",
            required_document_types=["Gesellschaftsvertrag"],
            matched_document_ids=[],
            explanation="Dieser Schritt wird durch einen Gesellschaftsvertrag oder eine Musterstruktur belegt.",
        ),
        FoundingCheck(
            id="capital_overview",
            category="Gründungsdokumente",
            title="Kapitalübersicht erstellen",
            description="Dokumentiert Stammkapital, Einlagen und Beteiligungsverhältnisse.",
            status="missing",
            required_document_types=["Kapitalübersicht"],
            matched_document_ids=[],
            explanation="Die Kapitalübersicht macht die Beteiligungsverhältnisse nachvollziehbar.",
        ),
        FoundingCheck(
            id="legal_form_path",
            category="Gründungsdokumente",
            title="Rechtsformpfad dokumentieren",
            description="Dokumentiert, dass der Pilot exemplarisch den UG-Pfad nutzt.",
            status="check",
            required_document_types=[],
            matched_document_ids=[],
            explanation="Wird automatisch gesetzt, sobald der UG-Pilotpfad aktiviert wurde.",
        ),
        FoundingCheck(
            id="trade_registration",
            category="Anmeldung & Behörden",
            title="Gewerbeanmeldung vorbereiten",
            description="Bereitet Angaben und Unterlagen für eine mögliche Gewerbeanmeldung vor.",
            status="missing",
            required_document_types=["Gewerbeanmeldung"],
            matched_document_ids=[],
            explanation="Eine vorbereitete Checkliste reduziert Rückfragen im weiteren Prozess.",
        ),
        FoundingCheck(
            id="tax_data",
            category="Anmeldung & Behörden",
            title="Steuerdaten erfassen",
            description="Sammelt Angaben für steuerliche Registrierung und Kommunikation mit dem Finanzamt.",
            status="missing",
            required_document_types=["Steuerdaten"],
            matched_document_ids=[],
            explanation="Steuerliche Basisdaten werden im Pilot über ein separates Dokument gebündelt.",
        ),
        FoundingCheck(
            id="register_notary_step",
            category="Anmeldung & Behörden",
            title="Register-/Notarschritt vormerken",
            description="Markiert den Schritt für notarielle oder registerbezogene Folgeprozesse.",
            status="check",
            required_document_types=[],
            matched_document_ids=[],
            explanation="Dieser Punkt dient im Pilot als Merkposten für spätere Offline-Schritte.",
        ),
        FoundingCheck(
            id="website_planned",
            category="Website & Datenschutz",
            title="Website geplant prüfen",
            description="Prüft, ob eine Website geplant oder bereits vorhanden ist.",
            status="done",
            required_document_types=[],
            matched_document_ids=[],
            explanation="Die Demo geht bereits von einer geplanten oder bestehenden Website aus.",
        ),
        FoundingCheck(
            id="imprint",
            category="Website & Datenschutz",
            title="Impressum vorbereiten",
            description="Bereitet die Anbieterkennzeichnung für eine geschäftliche Website vor.",
            status="missing",
            required_document_types=["Impressum"],
            matched_document_ids=[],
            explanation="Ein Impressumsdokument oder eine Checkliste belegt diesen Vorbereitungsschritt.",
        ),
        FoundingCheck(
            id="privacy_basics",
            category="Website & Datenschutz",
            title="Datenschutz-Basischeck durchführen",
            description="Prüft grundlegende Datenschutzfragen, insbesondere bei personenbezogenen Daten.",
            status="missing",
            required_document_types=["Datenschutz-Basischeck"],
            matched_document_ids=[],
            explanation="Bei personenbezogenen Daten erwartet der Pilot einen Datenschutz-Basischeck als Nachweis.",
        ),
        FoundingCheck(
            id="ai_usage",
            category="KI-Nutzung",
            title="KI-Nutzung erfassen",
            description="Erfasst, ob KI-Tools im Geschäftsmodell oder in Prozessen genutzt werden.",
            status="done",
            required_document_types=[],
            matched_document_ids=[],
            explanation="Die Demo markiert die geplante KI-Nutzung bereits als erfasst.",
        ),
        FoundingCheck(
            id="ai_use_case_sheet",
            category="KI-Nutzung",
            title="AI-Use-Case-Steckbrief erstellen",
            description="Dokumentiert Zweck, Kontext und Grenzen der geplanten KI-Nutzung.",
            status="missing",
            required_document_types=["AI-Use-Case-Steckbrief"],
            matched_document_ids=[],
            explanation="Der Steckbrief ist der zentrale Nachweis für die geplante KI-Nutzung.",
        ),
        FoundingCheck(
            id="ai_evidence",
            category="KI-Nutzung",
            title="Nachweise zur KI-Nutzung sammeln",
            description="Sammelt Nachweise, Beschreibungen oder Dokumentationen zur KI-Nutzung.",
            status="check",
            required_document_types=["AI-Use-Case-Steckbrief"],
            matched_document_ids=[],
            explanation="Weitere KI-Nachweise werden auf Basis des Steckbriefs technisch gemappt.",
        ),
    ]

    document_templates = [
        DocumentTemplate(
            id="template-founder-profile",
            title="Gründer:innenprofil",
            category="Basisdaten",
            description="Sammelt Namen, Rollen und Kontaktinformationen der Gründer:innen.",
            document_type="Gründer:innenprofil",
            template_type="portfolio",
        ),
        DocumentTemplate(
            id="template-company-profile",
            title="Unternehmensprofil",
            category="Basisdaten",
            description="Beschreibt Name, Zweck, Sitz und Kerndaten des Unternehmens.",
            document_type="Unternehmensprofil",
            template_type="portfolio",
        ),
        DocumentTemplate(
            id="template-articles",
            title="Gesellschaftsvertrag / Musterstruktur",
            category="Gründungsdokumente",
            description="Strukturiert die gesellschaftsrechtliche Grundordnung der UG.",
            document_type="Gesellschaftsvertrag",
            template_type="portfolio",
        ),
        DocumentTemplate(
            id="template-capital",
            title="Kapitalübersicht",
            category="Gründungsdokumente",
            description="Erfasst Stammkapital, Einlagen und Beteiligungsquoten.",
            document_type="Kapitalübersicht",
            template_type="portfolio",
        ),
        DocumentTemplate(
            id="template-address",
            title="Geschäftsadresse-Nachweis",
            category="Basisdaten",
            description="Hält Geschäftsanschrift oder Sitz der Gesellschaft fest.",
            document_type="Geschäftsadresse-Nachweis",
            template_type="portfolio",
        ),
        DocumentTemplate(
            id="template-trade",
            title="Gewerbeanmeldung-Checkliste",
            category="Anmeldung & Behörden",
            description="Bereitet die Angaben für eine spätere Gewerbeanmeldung vor.",
            document_type="Gewerbeanmeldung",
            template_type="checklist",
        ),
        DocumentTemplate(
            id="template-tax",
            title="Steuerdaten-Checkliste",
            category="Anmeldung & Behörden",
            description="Sammelt zentrale Informationen für die steuerliche Erfassung.",
            document_type="Steuerdaten",
            template_type="checklist",
        ),
        DocumentTemplate(
            id="template-imprint",
            title="Impressum-Checkliste",
            category="Website & Datenschutz",
            description="Strukturiert die Anbieterkennzeichnung für die Website.",
            document_type="Impressum",
            template_type="checklist",
        ),
        DocumentTemplate(
            id="template-privacy",
            title="Datenschutz-Basischeck",
            category="Website & Datenschutz",
            description="Bündelt die wesentlichen Datenschutzfragen im POC-Kontext.",
            document_type="Datenschutz-Basischeck",
            template_type="checklist",
        ),
        DocumentTemplate(
            id="template-ai-use-case",
            title="AI-Use-Case-Steckbrief",
            category="KI-Nutzung",
            description="Dokumentiert Einsatz, Zweck und Grenzen geplanter KI-Tools.",
            document_type="AI-Use-Case-Steckbrief",
            template_type="worksheet",
        ),
    ]

    knowledge_base = [
        KnowledgeItem(
            term="Impressum",
            category="Website & Datenschutz",
            explanation="Im Pilot beschreibt das Impressum die Anbieterkennzeichnung für eine geschäftliche Website.",
        ),
        KnowledgeItem(
            term="Datenschutzerklärung",
            category="Website & Datenschutz",
            explanation="Die Datenschutzerklärung erläutert, wie personenbezogene Daten verarbeitet werden und wird hier nur als Kontextbegriff geführt.",
        ),
        KnowledgeItem(
            term="personenbezogene Daten",
            category="Website & Datenschutz",
            explanation="Personenbezogene Daten sind Informationen, die sich auf eine identifizierte oder identifizierbare Person beziehen.",
        ),
        KnowledgeItem(
            term="beschränkte Haftung",
            category="Rechtsform",
            explanation="Beschränkte Haftung bedeutet im Pilotkontext, dass die persönliche Haftung der Gründer:innen grundsätzlich von der Gesellschaft getrennt gedacht wird.",
        ),
        KnowledgeItem(
            term="Gesellschaftsvertrag",
            category="Gründungsdokumente",
            explanation="Der Gesellschaftsvertrag hält die Grundregeln der Gesellschaft fest und dient im Pilot als zentraler Strukturbeleg.",
        ),
        KnowledgeItem(
            term="Gewerbeanmeldung",
            category="Anmeldung & Behörden",
            explanation="Die Gewerbeanmeldung steht im Pilot für den vorbereitenden Schritt Richtung zuständiger Behörde.",
        ),
        KnowledgeItem(
            term="Steuernummer",
            category="Anmeldung & Behörden",
            explanation="Die Steuernummer ist eine steuerliche Referenz; im Pilot wird hierzu ein strukturierendes Datendokument vorgesehen.",
        ),
        KnowledgeItem(
            term="wirtschaftlich Berechtigte",
            category="Gründungskontext",
            explanation="Wirtschaftlich Berechtigte sind Personen mit maßgeblichem wirtschaftlichem Einfluss auf das Unternehmen.",
        ),
        KnowledgeItem(
            term="Nachweis / Evidence",
            category="Evidence Buddy",
            explanation="Ein Nachweis ist im Pilot ein Dokument oder Dokumentinhalt, der einem Check technisch zugeordnet werden kann.",
        ),
        KnowledgeItem(
            term="KI-Nutzung",
            category="KI-Nutzung",
            explanation="KI-Nutzung beschreibt im Pilot, dass KI-Tools für Produkt, Service oder interne Prozesse vorgesehen sind.",
        ),
    ]

    return AppState(
        founder_case=founder_case,
        checks=checks,
        document_templates=document_templates,
        documents=[],
        evidence_records=[],
        knowledge_base=knowledge_base,
        disclaimer=DISCLAIMER,
    )

